<?php

/**
 * BaseFileStatusLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $file_status_id
 * @property timestamp $opened_at
 * @property timestamp $closed_at
 * @property File $File
 * @property FileStatus $FileStatus
 * 
 * @method integer       getFileId()         Returns the current record's "file_id" value
 * @method integer       getFileStatusId()   Returns the current record's "file_status_id" value
 * @method timestamp     getOpenedAt()       Returns the current record's "opened_at" value
 * @method timestamp     getClosedAt()       Returns the current record's "closed_at" value
 * @method File          getFile()           Returns the current record's "File" value
 * @method FileStatus    getFileStatus()     Returns the current record's "FileStatus" value
 * @method FileStatusLog setFileId()         Sets the current record's "file_id" value
 * @method FileStatusLog setFileStatusId()   Sets the current record's "file_status_id" value
 * @method FileStatusLog setOpenedAt()       Sets the current record's "opened_at" value
 * @method FileStatusLog setClosedAt()       Sets the current record's "closed_at" value
 * @method FileStatusLog setFile()           Sets the current record's "File" value
 * @method FileStatusLog setFileStatus()     Sets the current record's "FileStatus" value
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaseFileStatusLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_status_log');
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('opened_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('closed_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FileStatus', array(
             'local' => 'file_status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}