#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst 

dbc_dbname=MCP
dbc_dbuser=demo

dbc_go archivematica-mcp-server $@

adduser --uid 333 --group --system --no-create-home --disabled-login archivematica
chown -R archivematica:archivematica "/var/archivematica/"
chmod -R g+s "/var/archivematica/"
chmod -R 775 "/var/archivematica/"
echo "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/gs,/usr/lib/transcoder/transcoderScripts/DocumentConverter.py" >> /etc/sudoers
