#!/bin/sh

#Create Database and users
databaseName="MCP"
username="demo"
password="demo"

mysqladmin create "$databaseName"

mysql --execute="CREATE USER '${username}'@'localhost' IDENTIFIED BY '${password}'"
mysql --execute="GRANT SELECT, UPDATE, INSERT ON ${databaseName}.* TO '${username}'@'localhost'"


