# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1234390357);
user_pref("app.update.lastUpdateTime.background-update-timer", 1234390356);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1234390356);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1234390357);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1234390358);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 1);
user_pref("browser.places.createdSmartBookmarks", true);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.startup.homepage", "http://localhost");
user_pref("extensions.enabledItems", "firebug@software.joehewitt.com:1.2.0a21X,ubufox@ubuntu.com:0.5,{a6fd85ed-e919-4a43-a5af-8da18bda539f}:1.0b2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.0");
user_pref("extensions.lastAppVersion", "3.0b5");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1236982360);
