<?php

/**
 * Sip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class Sip extends BaseSip
{

  public function getStatus()
  {
    $q = Doctrine_Query::create()
      ->from('SipStatus s')
      ->leftJoin('s.SipStatusLogs l')
      ->where('l.sip_id = ?', $this->getId())
      ->andWhere('l.closed_at IS NULL');
 
    return $q->fetchOne();
  }
}
