<?php

/**
 * BaseSipStatusLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sip_id
 * @property integer $sip_status_id
 * @property timestamp $opened_at
 * @property timestamp $closed_at
 * @property Sip $Sip
 * @property SipStatus $SipStatus
 * 
 * @method integer      getSipId()         Returns the current record's "sip_id" value
 * @method integer      getSipStatusId()   Returns the current record's "sip_status_id" value
 * @method timestamp    getOpenedAt()      Returns the current record's "opened_at" value
 * @method timestamp    getClosedAt()      Returns the current record's "closed_at" value
 * @method Sip          getSip()           Returns the current record's "Sip" value
 * @method SipStatus    getSipStatus()     Returns the current record's "SipStatus" value
 * @method SipStatusLog setSipId()         Sets the current record's "sip_id" value
 * @method SipStatusLog setSipStatusId()   Sets the current record's "sip_status_id" value
 * @method SipStatusLog setOpenedAt()      Sets the current record's "opened_at" value
 * @method SipStatusLog setClosedAt()      Sets the current record's "closed_at" value
 * @method SipStatusLog setSip()           Sets the current record's "Sip" value
 * @method SipStatusLog setSipStatus()     Sets the current record's "SipStatus" value
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: BaseSipStatusLog.class.php 160 2010-02-25 00:53:31Z peter $
 */
abstract class BaseSipStatusLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sip_status_log');
        $this->hasColumn('sip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sip_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('opened_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('closed_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sip', array(
             'local' => 'sip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SipStatus', array(
             'local' => 'sip_status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}