<?php

/**
 * BaseAipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $icon
 * @property Doctrine_Collection $AipStatusLogs
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getIcon()          Returns the current record's "icon" value
 * @method Doctrine_Collection getAipStatusLogs() Returns the current record's "AipStatusLogs" collection
 * @method AipStatus           setName()          Sets the current record's "name" value
 * @method AipStatus           setIcon()          Sets the current record's "icon" value
 * @method AipStatus           setAipStatusLogs() Sets the current record's "AipStatusLogs" collection
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: BaseAipStatus.class.php 160 2010-02-25 00:53:31Z peter $
 */
abstract class BaseAipStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aip_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AipStatusLog as AipStatusLogs', array(
             'local' => 'id',
             'foreign' => 'aip_status_id'));
    }
}