<?php

/**
 * BaseSipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $icon
 * @property Doctrine_Collection $SipStatusLogs
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getIcon()          Returns the current record's "icon" value
 * @method Doctrine_Collection getSipStatusLogs() Returns the current record's "SipStatusLogs" collection
 * @method SipStatus           setName()          Sets the current record's "name" value
 * @method SipStatus           setIcon()          Sets the current record's "icon" value
 * @method SipStatus           setSipStatusLogs() Sets the current record's "SipStatusLogs" collection
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: BaseSipStatus.class.php 160 2010-02-25 00:53:31Z peter $
 */
abstract class BaseSipStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sip_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SipStatusLog as SipStatusLogs', array(
             'local' => 'id',
             'foreign' => 'sip_status_id'));
    }
}