<?php

/**
 * BaseFormatRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $format_id
 * @property integer $file_id
 * @property string $role
 * @property Format $Format
 * @property File $File
 * 
 * @method integer    getFormatId()  Returns the current record's "format_id" value
 * @method integer    getFileId()    Returns the current record's "file_id" value
 * @method string     getRole()      Returns the current record's "role" value
 * @method Format     getFormat()    Returns the current record's "Format" value
 * @method File       getFile()      Returns the current record's "File" value
 * @method FormatRole setFormatId()  Sets the current record's "format_id" value
 * @method FormatRole setFileId()    Sets the current record's "file_id" value
 * @method FormatRole setRole()      Sets the current record's "role" value
 * @method FormatRole setFormat()    Sets the current record's "Format" value
 * @method FormatRole setFile()      Sets the current record's "File" value
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: BaseFormatRole.class.php 160 2010-02-25 00:53:31Z peter $
 */
abstract class BaseFormatRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('format_role');
        $this->hasColumn('format_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Format', array(
             'local' => 'format_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}