<?php

/**
 * FormatRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class FormatRole extends BaseFormatRole
{
}
