#!/bin/sh

# This file is part of Archivematica.
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

# @package Archivematica
# @subpackage Ingest
# @author Joseph Perry <joseph@artefactual.com>
# @version svn: $Id$

#!!! this is a list of supported commands, not modules

#Commands
#the version numbers are versions of the protocol, not versions of the programs themselves.
echo_v1.0="/bin/echo "
FITS_v0.0="/opt/externals/fits/fits.sh "
easyExtract_v0.0="python /opt/externals/easy-extract/easy_extract.py "
setFilePermission_v0.0="chmod "
restructureToObjectsAndLogs_v0.0="%clientScriptsDirectory%restructureToObjectsAndLogs.sh "
createOrMoveAndCheckMD5_v0.0="%clientScriptsDirectory%createOrMoveAndCheckMD5.sh "
createOrMoveDC_v0.0="%clientScriptsDirectory%createOrMoveDC.sh "
clamscan_v0.0="clamscan "
#clamscan_v0.0="echo " #faster for testing
detox_v0.0="detox "
UUID4_v0.0="%clientScriptsDirectory%assignFileUUIDs.sh "
createMETS_v0.0="/usr/bin/archivematicaCreateMETS.py "
addDCTOMETS_v0.0="/usr/bin/archivematicaAddDublinCoreToMETS.py "
normalize_v0.0="/usr/bin/archivematicaNormalize.py "
createDirectory_v0.0="mkdir "
copy_v0.0="cp "
move_v0.0="mv "
bagit_v0.0="/opt/externals/bagit/bin/bag "
moveDetoxLogToDetoxedDirectory_v0.0="%clientScriptsDirectory%moveDetoxLogToDetoxedDirectory.py"
