#!/bin/sh

set -e

DIRECTORY="/var/log/archivematica"
userID=`id -u archivematica`

if [ $userID==333 ]; then
  echo "User archivematica exists""
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

if [ ! -d /var/log/archivematica ]; then
  mkdir -p /var/log/archivematica
  chown archivematica:archivematica /var/log/archivematica
fi