#!/bin/sh

set -e

USERID="archivematica"
DIRECTORY="/var/log/archivematica"


egrep  -i "^${USERID}" /etc/passwd
if [ $? -eq 0 ]; then
  echo "User $USERID exists in /etc/passwd"
else
  echo "adding archivematica user"
  sudo adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi


#echo "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/unoconv" >> /etc/sudoers


if [ ! -d "$DIRECTORY" ]; then
  mkdir -p /var/log/archivematica
  chown archivematica:archivematica /var/log/archivematica
fi


##instead of checking for the config files check status of upstart service
#if [ -e "/etc/init/openoffice-service.conf" ]; then
#  start openoffice-service
#fi

#if [ -e "/etc/init/archivematica-mcp-client.conf" ]; then
#  start archivematica-mcp-client
#fi
