<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/14 21:27:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dashboard',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
