#!/bin/bash

(for file in $@; do
	if [ -d "$file" ]; then
		echo "if"
		file_clean=${file//[ ()&\'\,]/_}
  		cleandirectory=`basename "$file_clean"`
  		echo $cleandirectory
		mv "$file" /home/demo/quarantine/$cleandirectory
		shortcleanpath="/home/demo/quarantine/$cleandirectory"
		echo $shortcleanpath		
		find $shortcleanpath -type f -print| while read FILE
			do
				file_clean=${FILE//[ ()&\'\,]/_}
				shortcleanfile=`basename "$file_clean"`
		 		echo $shortcleanfile
				/usr/local/OAIS/fits/access.sh  $shortcleanpath/$shortcleanfile
				shift
			done
		chmod -R 000 $shortcleanpath
	elif [ -f "$file" ]; then
		echo "elif"
		file_clean=${file//[ ()&\'\,]/_}
  		shortcleanfile=`basename "$file_clean"`
  		echo $shortcleanfile
		mv "$file" /home/demo/quarantine/$shortcleanfile 
		/usr/local/OAIS/fits/access.sh  ~/quarantine/$shortcleanfile
		chmod 000 ~/quarantine/$shortcleanfile
  		shift
	else
		echo "$file is not a file or directory"
	fi
done) 
#|zenity --progress --title "Accession in progress" --text "Processing" --pulsate --auto-close
