<?php

/**
 * FormGeneratorTest3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class FormGeneratorTest3 extends BaseFormGeneratorTest3
{
}
