#!/bin/bash
## MODIFIED FOR BAGCHECK
# AUTHOR:	(c) Tony Mattsson <tony_mattsson@home.se>
# VERSION:	1.0
# LICENSE:	GPL (http://www.gnu.org/licenses/gpl.html)
# REQUIRES:	gxmessage, md5sum, mawk, zenity
# NAME:		Check md5
# DESCRIPTION:	Checks the md5 hash checksum of files listed in a .md5-file


# Language settings

               Passed="true"
               Failed="error"
               PrintAllOk="All files are OK!"
               PrintFail1="file(s) are OK and"
               PrintFail2="file(s) are corrupt!"

for File in "$@"
do
 if [[ ${File:(( ${#File} -4 )):4} != ".zip" ]];then
    zenity --error --title="Check Bag" --text="This is not a '.zip' bag file."
    exit
 fi
# 1 Check the md5 file
(/opt/externals/bagit/bin/bag verifyvalid "$File" > /tmp/bagcheck.txt) 2>&1 | zenity --progress --title "Check Bag" --text "Checking: $File" --pulsate --auto-close


# 2 Display the results!

# Print a little repport about how many failed and how many passed
NumberOK=`cat /tmp/bagcheck.txt | fgrep -o -e "$Passed" | wc -l`
NumberFailed=`cat /tmp/bagcheck.txt | fgrep -o -e "$Failed" | wc -l`
   if [ $NumberFailed == 0 ]; then
       StatusMessage="$PrintAllOk"
   else
       StatusMessage="$NumberOK $PrintFail1 $NumberFailed $PrintFail2"
   fi
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> /tmp/bagcheck.txt
echo "$StatusMessage" >> /tmp/bagcheck.txt


zenity --text-info --title "$File" --width=640 --height=480 --filename=/tmp/bagcheck.txt

done

