#!/bin/bash

# This file is part of Archivematica.
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.


# @package Archivematica
# @subpackage Prepare AIP
# @author Austin Trask <austin@artefactual.com>
# @version svn: $Id$

NOW=$(date +"%F")
BAGNAME=`echo $@ | sed 's/ /_/g'`
BAGBASE=`basename $BAGNAME`

#BAG NAME SELECTION
CheckName=`zenity --entry --title="Bagit!" --entry-text "$BAGBASE-$NOW.zip" --text="Enter the name of your bag"`
if [ "$?" == 1 ] ; then exit ; fi

# BAG THE FILE
(/opt/externals/bagit/bin/bag create ~/recieveAIP/"$CheckName" "$@" --writer zip) 2>&1 | zenity --progress --title "Bagit!" --text "Bagging $CheckName" --pulsate --auto-close
