#!/bin/bash

NOW=$(date +"%F")
BAGNAME=`echo $@ | sed 's/ /_/g'`
BAGBASE=`basename $BAGNAME`



#BAG NAME SELECTION
CheckName=`zenity --entry --title="Bagit!" --entry-text "$BAGBASE-$NOW.zip" --text="Enter the name of your bag"`
if [ "$?" == 1 ] ; then exit ; fi

# BAG THE FILE
(/opt/OAIS/bagit/bin/bag create ~/recieveAIP/"$CheckName" "$@" --writer zip) 2>&1 | zenity --progress --title "Bagit!" --text "Bagging $CheckName" --pulsate --auto-close

