#!/bin/bash

if [ "0" == "$#" ] ; then
zenity --error --title="Sanitize files error" --text="Please select one or more files."
else
(
i=0
for f in "$@"; do 
echo $(($i * 100 / $#))
i=$(($i+1))
/opt/archivematica/sanitize "$f"  
sleep 1
done
echo 100
)|zenity --progress --title="Sanitize Files" --text="Sanitizing $# files" --auto-close
fi
