#! /bin/sh
# /etc/init.d/unoconv-listen
#


case "$1" in
  start)
    echo "Starting Unoconv-listener "
    /usr/bin/unoconv --listener &
    ;;
  stop)
    echo "Stopping Unoconv-listener "
    killall soffice.bin
    ;;
  restart)
    \$0 stop \$0 start
    ;;
  *)
    echo "Usage: /etc/init.d/unoconv-listen {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

