#!/bin/sh

set -e

#source debconf stuff
. /usr/share/debconf/confmodule

dbc_dbname=MCP
dbc_dbuser=archivematica

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/config.mysql
  dbc_go archivematica-transcoder $@
fi

if [ -x "/etc/init.d/openofficed" ]; then
        update-rc.d openofficed defaults >/dev/null
        invoke-rc.d openofficed start || exit $?
fi
