#!/bin/bash

# upload-qubit script location
UPLOAD_QUBIT_PATH="${HOME}/archivematica/src/upload-qubit/upload-qubit"

# Qubit URL and login
URL="http://localhost/ica-atom/index.php/sword/deposit/archivematica"
LOGIN="demo@example.com demo"

# DIP path
DIP="~/PeanutDIP"

# If you are using "referenced-rsync" mode
RSYNC_CMD="ssh -l YOURUSERNAME -p 22"
RSYNC_TO="remote.host.tld:~/deposits"

if [ "$1" = "1" ]; then

  ${UPLOAD_QUBIT_PATH} \
    attached \
    ${URL} \
    ${LOGIN} \
    ${DIP} debug

elif [ "$1" = "2" ]; then

  ${UPLOAD_QUBIT_PATH} \
    referenced \
    ${URL} \
    ${LOGIN} \
    ${DIP}

elif [ "$1" = "3" ]; then

  ${UPLOAD_QUBIT_PATH} \
    referenced-sync \
    ${URL} \
    ${LOGIN} \
    ${DIP} \
    ${RSYNC_CMD} \
    ${RSYNC_TO}

else

  echo "1 = attached"
  echo "2 = referenced"
  echo "3 = referenced-rsync"
  exit

fi

echo "Exit status: $?"
