<?php

/**
 * AipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: AipStatus.class.php 160 2010-02-25 00:53:31Z peter $
 */
class AipStatus extends BaseAipStatus
{
}
