<?php

/**
 * Format
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dashboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Format.class.php 160 2010-02-25 00:53:31Z peter $
 */
class Format extends BaseFormat
{
}
